##SUPPORT VECTOR MACHINES PROJECT
#DATA
loans <- read.csv('loan_data.csv')
summary(loans)
str(loans)
loans$inq.last.6mths <- factor(loans$inq.last.6mths)
loans$delinq.2yrs <- factor(loans$delinq.2yrs)
loans$pub.rec <- factor(loans$pub.rec)
loans$not.fully.paid <- factor(loans$not.fully.paid)
loans$credit.policy <- factor(loans$credit.policy)
#EDA
library(ggplot2)
pl <- ggplot(loans, aes(x=fico)) + geom_histogram(aes(fill=not.fully.paid), color='black', bins=40, alpha=0.5) + scale_fill_manual(values = c('green','red')) + theme_bw()
print(pl)                                       
pl2 <- ggplot(loans, aes(x=factor(purpose))) + geom_bar(aes(fill=not.fully.paid), position='dodge') + theme_bw() + theme(axis.text.x = element_text(angle=90, hjust=1))
print(pl2)
pl3 <- ggplot(loans, aes(x=int.rate, fico)) + geom_point(aes(color=not.fully.paid), alpha=0.3) + theme_bw()
print(pl3)
#BUILDING THE MODEL
library(caTools)
set.seed(101)
split <- sample.split(loans$not.fully.paid, SplitRatio=0.7)
train <- subset(loans, split==TRUE)
test <- subset(loans, split==FALSE)
library(e1071)
model <- svm(not.fully.paid~., data=train)
summary(model)
predicted.values <- predict(model, test[1:13])
table(predicted.values, test$not.fully.paid)
#TUNING THE MODEL
tune.results <- tune(svm, train.x=not.fully.paid~., data=train, kernel='radial', ranges=list(cost=c(1,10), gamma=c(0.1,1)))
model <- svm(not.fully.paid ~., data=train, cost=10, gamma=0.1)
predicted.values <- predict(model, test[1:13])
table(predicted.values, test$not.fully.paid)
summary(tune.results)
